### ISSUE TITLE
Add description and instructions for session 3

### ISSUE THREAD

**Issue by francojc** [WFU-TLC/wfu-tlc.github.io#11]
As discussed yesterday, I will update the information on the Session page for session 3. This may require some adjustments to session 2, given we didn't cover tidy-data principles in session 2. 

Main ideas to cover in session 3: 

- importing/ exporting data (with the `rio` package)
- tidy data principles (contrasting tidy and untidy data)
- basic tabular and graphic summaries (`dplyr::count()` and `ggplot2::ggplot()` functions)

Then the idea would be to lead into **wrangling and exploring data** in more detail in session 4. 

Confirm this sounds about right. When you do, I'll get to updating the website.

**Comment by medewitt** [comment]
Yes! Sorry!
