### ISSUE TITLE
Git via terminal, RStudio, or other?

### ISSUE THREAD

**Issue by francojc** [WFU-TLC/wfu-tlc.github.io#6]
I was thinking it might be a good idea to get on the same page as to whether we want to teach Git in one way so simplify the introduction to versioning. I'm game for any one of the above options. Any feelings on this?

**Comment by medewitt** [comment]
It doesn't matter to me...I personally use a mix of the GUI and the terminal. When teaching I just teach the R Studio GUI so learners don't have any additional programming to do, but for long term use I think you need to know the terminal commands. That's my non-answer....

**Comment by francojc** [comment]
👍 
Yeah, I was looking over the Happy Git material and saw that it tends to be the case that people mix a GUI and terminal. I'm not that familiar with the RStudio interface, I've primarily used the terminal. I'll look forward to learning about RStudio/ Git integration.

**Comment by medewitt** [comment]
![image](https://user-images.githubusercontent.com/25038837/47454764-072d1600-d79e-11e8-8dce-582ee3afa837.png)

**Comment by medewitt** [comment]
![magnolia scholar](https://user-images.githubusercontent.com/25038837/47454866-43f90d00-d79e-11e8-8570-2f5f08d466f8.JPG)
