### ISSUE TITLE
Example Data Sets

### ISSUE THREAD

**Issue by medewitt** [WFU-TLC/wfu-tlc.github.io#9]
Need to Have Example Data Sets for others to pull during the class.

**Comment by medewitt** [comment]
Data are available here:

<http://users.wfu.edu/dewittme/data/sample/>

SPSS:
*  GSS2016.sav (General Social Survey Data)
*  Aug16_nr_public.sav (Pew Public Opinion)

Excel
*  SFY2017_Annual_Unduplicated_Enrollment_Counts_by_County_and_Budget_Groups_0.xlsx (NC Medicaid)

CSV
*  gapminder.csv Gapminder Data

Stata
*  sesame.dta

Participants can download to their local machine or read directly by attaching the file name to the above link

**Comment by francojc** [comment]
Awesome. The 'car' and 'languageR' packages have some good built-in datasets that may be of interest to our participants too.

**Comment by francojc** [comment]
Quick question: do you have the sources of this data? I ask because it would be helpful to find some documentation on the datasets so that we can understand what the attributes and values refer to. I started taking a look at the GSSD data and it's hard to make heads or tails about what each column represents.

**Comment by medewitt** [comment]
The gss data is from <http://gss.norc.org/get-the-data> unfortunately there isn't a good codebook just on the main site. Using `haven` the questions appear in the label attributes. Personally I then use Hmisc or the labelled package to do additional manipulations using the labels.

For the Pew Public Opinion data I added the supporting documents  <http://users.wfu.edu/dewittme/data/sample/aug16_nr_public>

The sesame codebook is located here: <http://www2.stat.duke.edu/~jerry/sta103/labs/lab8a.html>

I don't know if this helps because they'll know their data when the time comes. Always a challenge of learning the data and the tool at the same time....

**Comment by francojc** [comment]
I'm getting a forbidden response for the: http://users.wfu.edu/dewittme/data/sample/geocoded_incidents_with_census_data.csv data

**Comment by medewitt** [comment]
Yep, it is something on our server. I believe the file is 35mb and the server restricts it to files less than 25mb...I stuck that file there for my own purposes
